{% set name = "bc-python-hcl2" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bc-python-hcl2-{{ version }}.tar.gz
  sha256: ac8ff59fb9bd437ea29b89a7d7c507fd0a1e957845bae9aeac69f2892b8d681e

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - lark >=1.0.0
    - importlib-resources >=2.0.0  # [py<39]

test:
  imports:
    - hcl2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bridgecrewio/python-hcl2
  summary: A parser for HCL2
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - borchero
    - nick-harmening
